### ISSUE TITLE
Backend monitoring and metrics

### ISSUE THREAD

**Issue by sbc64** [WalletConnect-Labs/walletconnect-v2-monorepo#11]
- [x] Add prometheus package to the server
- [x] Add some basic metrics
    - [x] Dropped websocket connections
    - [x] Errors occured
    - [x] Keys that expired TTL
- ~[ ] Update health check bot~ This has been replaced by the health server https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/commit/ad3f1538a28ba220242db3979a765d72bc4b01d7
    - ~[ ] Send notifications when delay gets too high~
    - ~[ ] Failure notification~
    
EDIT: 2021-06-03 23:24

The health check bot functional has been replaced by the health server https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/commit/ad3f1538a28ba220242db3979a765d72bc4b01d7

Basic metrics as of right now is done but public grafana dashboard is still needed.

- [x] Public grafana dashboard

Public Dashboard: https://grafana.relay.walletconnect.org/

**Comment by yourbuddyconner** [comment]
Any ETA on when this issue lands? Awaiting it eagerly!

**Comment by sbc64** [comment]
There is already some metrics in the relay server. Look at: https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/blob/master/ops/grafana/provisioning/dashboards/relay.json

Just that for this issue there are some things that still need to be added to be considered complete, like the health check bot that should have better statistics over the hour and not just a single second during the hour time window.
