### ISSUE TITLE
Cross-platform testing

### ISSUE THREAD

**Issue by sbc64** [WalletConnect-Labs/walletconnect-v2-monorepo#13]
Cross-platform testing across browser, node-js and react-native

**Comment by pedrouid** [comment]
Include test cases for each Javascript platform:

Browser
- [ ] WebSocket Connection connects successfully
- [ ] WebSocket Connection sends and receives payloads successfully
- [ ] KeyValue storage is able to set and get values
- [ ] KeyValue storage is persisted and restored after restart

NodeJS
- [ ] WebSocket Connection connects successfully
- [ ] WebSocket Connection sends and receives payloads successfully
- [ ] KeyValue storage is able to set and get values
- [ ] KeyValue storage is persisted and restored after restart

React-Native
- [ ] WebSocket Connection connects successfully
- [ ] WebSocket Connection sends and receives payloads successfully
- [ ] KeyValue storage is able to set and get values
- [ ] KeyValue storage is persisted and restored after restart
