### ISSUE TITLE
Using defaults the ttl of the pairing is not 30 days

### ISSUE THREAD

**Issue by urkaitz** [WalletConnect-Labs/walletconnect-v2-monorepo#55]
#Steps to Reproduce
1. Create Proposer and set storage using keyvaluestorage to sqlite
2. Call connect on proposer
3. Take generated uri
4. Create a responser and call pair using uri
5. On responser approve session

#Expected Results
1. Read sqlite db
2. Pairing settled property expiry should be a timestamp of 30 days after now

#Actual Results
1. Read sqlite db
2. Pairing settled property expiry is 2592000 after now

The problem may be in the pairing controller, it expects the default ttl times to be in millis but they are defined in days.

**Comment by pedrouid** [comment]
Thanks for the catch @urkaitz 🙌 As mentioned on Discord I've fixed and published this under 2.0.0-alpha.35 which also included the change of TTL to 21 days (3 weeks) given the limitation of maximum timeout in Javascript of (32 bit signed integer)
