### ISSUE TITLE
My coin was mistakenly sent to you! Please can I get a refund

### ISSUE THREAD

**Issue by Mk04477** [WalletConnect-Labs/walletconnect-v2-monorepo#97]
0xc1542C48Fa0aeA80798448DA0b39627cf41471bb 

This is suppose to be my real Walter

**Comment by sbc64** [comment]
You likely fell for a scam. WalletConnect does not handle ethereum wallets and we don't receive coins ANYWHERE except for [Gitcoin.co](https://gitcoin.co/)

We are really sorry this happened to you.
